# https://taskfile.dev

version: '3'

includes:
  assigment:
    taskfile: ./assigment/Taskfile.yml
    dir: ./assigment
  slides-basic:
    taskfile: ./slides-basic/Taskfile.yml
    dir: ./slides-basic

tasks:
  clean:
    cmds:
      - task: assigment:clean
      - task: slides-basic:clean
      - rm -rf output.typ
